apiVersion: v1
kind: Service
metadata:
  name: multitool-service
spec:
  selector:
    app: multitool-app
  ports:
  - name: http-nginx
    port: 80
    targetPort: 80
    protocol: TCP
  - name: http-multitool
    port: 8080
    targetPort: 8080
    protocol: TCP
  type: ClusterIP
