apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-nginx
  labels:
    app: {{ .Chart.Name }}-nginx
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}-nginx
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}-nginx
    spec:
      containers:
      - name: nginx
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: 80
